# Generated by Django 5.0 on 2024-07-26 17:36

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tg', models.UUIDField(blank=True, null=True, unique=True, verbose_name='id в телеграмм')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название салона')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес салона')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.FloatField(verbose_name='Цена услуги')),
                ('duration', models.IntegerField(verbose_name='Длительность услуги, мин')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('cancel', 'Отменено')], max_length=14, verbose_name='Статус заказа')),
                ('receipt', models.URLField(blank=True, verbose_name='Чек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Счёт выставлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('access', 'Принято'), ('ended', 'Завершено'), ('discard', 'Отменено')], max_length=9, verbose_name='Статус заказа')),
                ('date', models.DateField()),
                ('start_at', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.client')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.order')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistWorkDayInSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday', models.DateField()),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.salon')),
                ('services', models.ManyToManyField(to='mybot.service', verbose_name='Услуги')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.specialist')),
            ],
        ),
    ]
